services:
  - type: web
    name: naive-ops-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: APPROVAL_BASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: LOGIN_APPROVER_EMAILS
        sync: false
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
